version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: boss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data_pg17:/var/lib/postgresql/data

volumes:
  db_data_pg17:
